# -*- coding: utf-8 -*-
"""Project 2. Customer Support Bot for FAQs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScKCGeFzEn2CohMW0yJxYXD_AB--Htfh
"""

# Install gradio if it's not already installed
!pip install gradio

# %%
import openai
import os
import gradio as gr

# Set your OpenAI API key
openai.api_key = os.getenv("OPENAI_API_KEY")  # or paste your key directly

# FAQ knowledge base (optional: load from file)
faq_context = """
FAQs:
Q: What are your business hours?
A: We are open Monday to Friday, 9 AM to 6 PM.

Q: How can I reset my password?
A: Click on 'Forgot Password' on the login page and follow the instructions.

Q: Where do you ship to?
A: We ship to all 50 U.S. states and select international locations.

Q: How can I contact support?
A: Email us at support@example.com or call 1-800-123-4567.
"""

def get_faq_response(user_input):
    messages = [
        {"role": "system", "content": "You are a helpful customer support agent. Use the FAQ information below to answer questions as accurately as possible.\n" + faq_context},
        {"role": "user", "content": user_input}
    ]
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Error: {str(e)}"

import gradio as gr

# FAQ knowledge base as a dictionary for easy lookup
faq_data = {
    "hours": "We are open Monday to Friday, 9 AM to 6 PM.",
    "business hours": "We are open Monday to Friday, 9 AM to 6 PM.",
    "open": "We are open Monday to Friday, 9 AM to 6 PM.",
    "reset password": "Click on 'Forgot Password' on the login page and follow the instructions.",
    "password": "Click on 'Forgot Password' on the login page and follow the instructions.",
    "ship": "We ship to all 50 U.S. states and select international locations.",
    "shipping": "We ship to all 50 U.S. states and select international locations.",
    "where do you ship": "We ship to all 50 U.S. states and select international locations.",
    "contact": "Email us at support@example.com or call 1-800-123-4567.",
    "support": "Email us at support@example.com or call 1-800-123-4567.",
    "contact support": "Email us at support@example.com or call 1-800-123-4567."
}

def get_faq_response_rule_based(user_input):
    user_input_lower = user_input.lower()

    # Try to find a direct match for the question
    for question_phrase, answer in faq_data.items():
        if question_phrase in user_input_lower:
            return answer

    # If no direct match, try to find keywords
    if "hours" in user_input_lower or "open" in user_input_lower:
        return faq_data["hours"]
    elif "password" in user_input_lower or "reset" in user_input_lower:
        return faq_data["password"]
    elif "ship" in user_input_lower or "shipping" in user_input_lower:
        return faq_data["ship"]
    elif "contact" in user_input_lower or "support" in user_input_lower:
        return faq_data["contact"]
    else:
        return "I'm sorry, I don't have information on that. Please try rephrasing your question or contact support directly via support@example.com."

# Create a simple Gradio interface
iface = gr.Interface(
    fn=get_faq_response_rule_based,
    inputs="text",
    outputs="text",
    title="Customer Support FAQ Bot (Rule-Based)",
    description="Ask any frequently asked question. Example: 'What are your business hours?' This bot uses simple rules."
)

iface.launch()